import assert from 'node:assert/strict';
import {sampleOrder,sampleStocks,matchStock} from '../lib/cutting.ts';
import {baselineSummary,validateFeedback} from '../lib/evidence.ts';
import {createRouteHarness} from './route-harness.mjs';
const harness=createRouteHarness(), fetch=harness.fetch;

// Local-only, independent anonymous users. All entries are synthetic test fixtures.
const endpoint='http://127.0.0.1:4173/api/workshop';
async function actor(name){
 const response=await fetch(endpoint);assert.equal(response.status,200);
 const cookie=response.headers.get('set-cookie')?.split(';')[0];assert.ok(cookie);
 const headers={'Content-Type':'application/json',Cookie:cookie,Origin:'http://127.0.0.1:4173'};
 return {name,cookie,state:await response.json(),async get(){return (await fetch(endpoint,{headers})).json();},async post(body){const r=await fetch(endpoint,{method:'POST',headers,body:JSON.stringify(body)});return {status:r.status,data:await r.json()};}};
}
async function expect(actor,body,status=200){const r=await actor.post(body);assert.equal(r.status,status,JSON.stringify(r.data));if(status<300)actor.state=r.data;return r.data;}
const [seller,buyer,third]=await Promise.all([actor('Seller fixture'),actor('Buyer fixture'),actor('Other fixture')]);
assert.notEqual(seller.state.exchange.id,buyer.state.exchange.id);
for(const person of [seller,buyer,third])await expect(person,{action:'profile',profile:{name:person.name,suburb:'Synthetic suburb',contact:'Use pickup conversation'}});
const personal=seller.state.exchange.id;
const personalRecord=await expect(seller,{action:'reserve',stockId:'OC-001',order:sampleOrder,approved:true,signature:matchStock(sampleStocks[0],sampleOrder).plan.signature},201);
await expect(seller,{action:'createExchange',name:'Synthetic integration exchange',includeSamples:false},201);
const scope=seller.state.exchange.id,code=seller.state.exchange.inviteCode;
assert.equal(seller.state.stocks.length,0);
await expect(third,{action:'switchExchange',id:scope},403);
await expect(buyer,{action:'joinExchange',code:'CC-BAD'},400);
await expect(buyer,{action:'joinExchange',code});
await expect(buyer,{action:'joinExchange',code});
assert.equal(buyer.state.exchange.memberCount,2,'Joining is idempotent');
const listing={...sampleStocks[0],workshop:seller.name,suburb:'Synthetic suburb',defects:'Synthetic fixture: inspect a small edge mark.',pickupWindow:'Synthetic fixture: Tuesday 10 am by arrangement',pickupLocation:'Synthetic fixture loading area',sellerContact:'Use pickup conversation',alternativeRoute:'landfill',baselineNotes:'Synthetic fixture: seller reports disposal in a landfill skip.'};
await expect(seller,{action:'addStock',stock:{...listing,baselineNotes:''}},400);
await expect(seller,{action:'addStock',stock:listing},201);
const stock=seller.state.stocks[0];
assert.ok(stock.canEdit);assert.equal(stock.pickupWindow,listing.pickupWindow);
const sharedBuyer=await buyer.get();assert.equal(sharedBuyer.stocks[0].id,stock.id);assert.equal(sharedBuyer.stocks[0].canEdit,false);
const isolated=await third.get();assert.ok(!isolated.stocks.some(s=>s.id===stock.id));
await expect(buyer,{action:'stockDetails',id:stock.id,details:listing},403);
await expect(seller,{action:'stockDetails',id:stock.id,details:{...listing,defects:'Updated synthetic inspection note'}});
assert.equal(seller.state.stocks[0].defects,'Updated synthetic inspection note');
await expect(third,{action:'joinExchange',code});
const plan=matchStock(stock,sampleOrder).plan;
const reserve={action:'reserve',exchangeId:scope,stockId:stock.id,order:sampleOrder,approved:true,signature:plan.signature};
const race=await Promise.all([buyer.post(reserve),third.post(reserve)]);
assert.deepEqual(race.map(r=>r.status).sort(),[201,409],'Two buyers cannot claim one offcut');
const winner=race[0].status===201?buyer:third,other=winner===buyer?third:buyer;
const saved=race.find(r=>r.status===201).data,id=saved.createdId,record=saved.reservations.find(r=>r.id===id);
assert.equal(baselineSummary(saved.reservations,true).landfillArea,0,'Reservations alone have no impact');
assert.equal(record.stock.defects,'Updated synthetic inspection note');assert.ok(record.stock.baselineRecordedAt);
assert.equal((await seller.get()).notifications.filter(n=>n.recordId===id&&n.title==='New offcut reservation').length,1,'Notify seller once');
for(const body of [{action:'advance',id,status:'collected'},{action:'cancel',id},{action:'message',id,body:'Unauthorized fixture'},{action:'stockDetails',id:stock.id,details:listing}])await expect(other,body,403);
await expect(seller,{action:'advance',id,status:'collected'},403);
await expect(seller,{action:'stockDetails',id:stock.id,details:listing},409);
await expect(winner,{action:'message',id,body:'Synthetic buyer: can I collect at 10 am?'});
await expect(seller,{action:'message',id,body:'Synthetic seller: yes, use the loading area.'});
const conversation=(await winner.get()).reservations.find(r=>r.id===id);
assert.equal(conversation.messages.length,2);assert.equal(conversation.messages[0].mine,true);
const outsider=await other.get();assert.deepEqual(outsider.reservations.find(r=>r.id===id).messages,[]);assert.equal(outsider.notifications.length,0);
const responseText=JSON.stringify(outsider);
for(const hidden of [seller.cookie.slice(13),winner.cookie.slice(13)])assert.ok(!responseText.includes(hidden),'Do not expose other users’ internal identifiers');
await expect(winner,{action:'advance',id,status:'reused',usedIds:[plan.placements[0].id],avoidedNew:'unknown'},409);
await expect(winner,{action:'advance',id,status:'collected'});
assert.equal(baselineSummary(winner.state.reservations,true).landfillArea,0,'Collection alone has no impact');
await expect(winner,{action:'advance',id,status:'reused',usedIds:['invented'],avoidedNew:'unknown'},400);
await expect(winner,{action:'advance',id,status:'reused',usedIds:[plan.placements[0].id],weightKg:null,avoidedNew:'unknown',notes:'Synthetic partial-completion test'});
const impact=baselineSummary(winner.state.reservations,true);
assert.equal(impact.landfillArea,159200);assert.equal(impact.documented,1);assert.equal(impact.completed,1);
assert.equal(winner.state.reservations.find(r=>r.id===id).weightKg,null);
const sample={source:'sample',workshop:'Synthetic maker example',date:new Date().toLocaleDateString('sv-SE',{timeZone:'Australia/Sydney'}),finding:'Fictional example only: pickup time is the main barrier.',canCut:'not_tested',wouldUse:'maybe',sourceNote:'Automated synthetic test',usualMinutes:null,matchingMinutes:null};
await expect(seller,{action:'addFeedback',feedback:{...sample,source:'interview'}},400);
await expect(seller,{action:'addFeedback',feedback:{...sample,workshop:123}},400);
await expect(seller,{action:'addFeedback',feedback:{...sample,date:'2026-02-30'}},400);
await expect(seller,{action:'addFeedback',feedback:sample},201);
assert.equal(seller.state.feedback.filter(f=>f.source!=='sample').length,0,'Synthetic feedback is not actual research');
assert.equal(validateFeedback({...sample,source:'trial',confirmedActual:true,sourceNote:'Validator fixture only; no trial is inserted'}).length,0);
assert.ok(validateFeedback({...sample,source:'trial',confirmedActual:true,sourceNote:''}).length);
// Verify sample resets leave non-sample entries alone, without claiming this fixture is real.
await expect(seller,{action:'addStock',stock:{...listing,demo:false,alternativeRoute:'unknown',baselineNotes:'Automated test of preservation; not real material.'}},201);
const kept=seller.state.stocks.find(s=>!s.demo).id;
await expect(other,{action:'resetDemo',confirm:true},403);
await expect(seller,{action:'readNotifications'});assert.ok(seller.state.notifications.every(n=>n.read));
await expect(seller,{action:'resetDemo',confirm:true});
assert.equal(seller.state.stocks.length,1);assert.equal(seller.state.stocks[0].id,kept);assert.equal(seller.state.feedback.length,0);assert.equal(seller.state.reservations.length,0);
await expect(seller,{action:'switchExchange',id:personal,exchangeId:scope});
assert.equal(seller.state.reservations.find(r=>r.id===personalRecord.createdId).status,'reserved','Original personal ledger is preserved');
await expect(seller,{action:'addStock',stock:listing,exchangeId:scope},409,'Reject an old-tab write into a different exchange');
await expect(seller,{action:'cancel',id:personalRecord.createdId});
assert.equal((await seller.get()).stocks.find(s=>s.id==='OC-001').status,'available');
const old=await (await fetch(endpoint,{headers:{Cookie:harness.legacyCookie}})).json();
assert.equal(old.stocks.find(s=>s.id==='OC-001').status,'collected');
assert.equal(old.reservations[0].id,'CC-LEGACY');assert.equal(old.reservations[0].canRecordReuse,true);
assert.equal(old.reservations[0].stock.alternativeRoute,undefined,'No retroactive landfill evidence is invented');
const legacyReuse=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Cookie:harness.legacyCookie},body:JSON.stringify({action:'advance',id:'CC-LEGACY',status:'reused',usedIds:[plan.placements[0].id],avoidedNew:'unknown'})});assert.equal(legacyReuse.status,200);
harness.close();
console.log('PASS: shared inventory, join isolation, three-user permissions, simultaneous booking, seller notifications, private pickup conversation, fixed baselines, completed-only partial impact, honest feedback, sample-reset preservation and stale-tab protection.');
