import { sqliteTable, text, real, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const offcuts=sqliteTable('offcuts',{owner:text('owner').notNull(),id:text('id').notNull(),data:text('data').notNull(),status:text('status').notNull(),sellerId:text('seller_id').notNull().default('')},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const reservations=sqliteTable('reservations',{owner:text('owner').notNull(),id:text('id').notNull(),stockId:text('stock_id').notNull(),stock:text('stock').notNull(),order:text('order_data').notNull(),plan:text('plan').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),revision:text('revision').notNull(),usedIds:text('used_ids').notNull().default('[]'),weightKg:real('weight_kg'),avoidedNew:text('avoided_new').notNull().default('unknown'),notes:text('notes').notNull().default(''),buyerId:text('buyer_id').notNull().default(''),sellerId:text('seller_id').notNull().default(''),buyerName:text('buyer_name').notNull().default(''),sellerName:text('seller_name').notNull().default('')},t=>[primaryKey({columns:[t.owner,t.id]})]);
export const profiles=sqliteTable('workshop_profiles',{owner:text('owner').primaryKey(),name:text('name').notNull(),suburb:text('suburb').notNull().default(''),contact:text('contact').notNull().default(''),activeExchange:text('active_exchange').notNull()});
export const exchanges=sqliteTable('exchanges',{id:text('id').primaryKey(),name:text('name').notNull(),createdBy:text('created_by').notNull(),inviteCode:text('invite_code').unique(),shared:integer('shared').notNull().default(0),sampleSeed:integer('sample_seed').notNull().default(1),createdAt:text('created_at').notNull()});
export const members=sqliteTable('exchange_members',{exchangeId:text('exchange_id').notNull(),memberId:text('member_id').notNull(),joinedAt:text('joined_at').notNull()},t=>[primaryKey({columns:[t.exchangeId,t.memberId]})]);
export const notifications=sqliteTable('exchange_notifications',{id:text('id').primaryKey(),exchangeId:text('exchange_id').notNull(),recipient:text('recipient').notNull(),recordId:text('record_id').notNull(),title:text('title').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull(),readAt:text('read_at')},t=>[index('notifications_recipient').on(t.exchangeId,t.recipient)]);
export const messages=sqliteTable('coordination_messages',{id:text('id').primaryKey(),exchangeId:text('exchange_id').notNull(),reservationId:text('reservation_id').notNull(),authorId:text('author_id').notNull(),authorName:text('author_name').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('messages_reservation').on(t.exchangeId,t.reservationId)]);
export const feedback=sqliteTable('pilot_feedback',{id:text('id').primaryKey(),exchangeId:text('exchange_id').notNull(),authorId:text('author_id').notNull(),data:text('data').notNull(),createdAt:text('created_at').notNull()},t=>[index('feedback_exchange').on(t.exchangeId)]);
